### PR TITLE
Drush tests

### PR DESCRIPTION
**Pull request by greg-1-anderson**
Add a failing test demonstrating that the Drush driver cannot create content without the Behat Drush Endpoint.

Next will come working tests.

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
Drupal 6 tests are passing (Drush Driver tests skipped), and Drupal 7 tests are passing (including Drush Driver tests).  The Drupal 8 tests are not passing, but these were previously not running, and there are some pre-existing problems.  Not sure at this point if I'm going to try to work through them all, or if perhaps I should just disable the Drush Driver on the Drupal 8 tests again, and fix d8 as a followon issue.

**Comment by greg-1-anderson** [comment]
Decided to just turn off Drupal 8 for now. If the tests are all green, you could merge this if you want. I will continue working on this, though, either here or in another PR.

**Comment by jhedstrom** [comment]
Hmm, unless I'm misreading this, it doesn't appear to be running the drush suite at all: https://travis-ci.org/jhedstrom/drupalextension/jobs/90537681#L612

**Comment by greg-1-anderson** [comment]
Did I Volkswagon it?  I'll take a look.

**Comment by greg-1-anderson** [comment]
Isn't the line you hilited the result of running the Drush suite a few lines up?  https://travis-ci.org/jhedstrom/drupalextension/jobs/90537681#L605

**Comment by jhedstrom** [comment]
> Isn't the line you hilited the result of running the Drush suite a few lines up?

Yep. I totally misread the output.

Merging now. Thanks!

**Pull request merged**
