### PR TITLE
WIP: Create an AuthenticationManager service

### PR DESCRIPTION
**Pull request by pfrenssen**
This is part of #316 which is an initiative to move all code in `RawDrupalContext` to services so its logic can be changed by projects that have customized the way they interact with Drupal.

In this PR an `AuthenticationManager` service will be provided that takes care of authenticating users in Drupal. We will provide a default implementation that matches the UI that Drupal core delivers out of the box.

People that need to customize the authentication procedure can swap out the default implementation with their own. Example use cases: Email Registration module, OAuth, Single Sign On.

### CODE REVIEW

**Comment by pfrenssen** [comment]
Refactoring is done. There was a random failure for which I created a followup #341 

Now that we have the service let's try if we can swap it out with another implementation. I will use Email Registration as an example.

The code for this should be contributed to the Email Registration module itself, but I'll put the initial implementation here for convenience. Once it's ready we can move it to the issue queue of Email Registration.

**Comment by pfrenssen** [comment]
I started on the integration with Email Registration but I finally opted to not do it here but in a dedicated issue for the Email Registration module. It was a bit too much trouble to create a dedicated test suite here.

Work in progress can be found here: https://github.com/pfrenssen/email_registration/pull/1 with corresponding drupal.org issue at https://www.drupal.org/node/2843505

**Comment by pfrenssen** [comment]
The patch for Email Registration is ready.

This now only needs some documentation that explains how people can override services.

**Comment by jonathanjfshaw** [comment]
I tried to test this but couldn't get it working. I get the message 
```
  [ReflectionException]
  Class Drupal\email_registration\Component\DrupalExtension\EmailRegistrationAuthenticationManager does not exist
```
when launching Behat.

In the composer.json require key I have
```
"drupal/drupal-driver": "dev-master",
"drupal/drupal-extension": "dev-master",
"friends-of-behat/service-container-extension": "~0.3",
```
and in the patches key I have:
```
"drupal/drupal-extension": {
   "Create an AuthenticationManager service": "https://github.com/jhedstrom/drupalextension/pull/339.patch"
            },
"drupal/email_registration": {
   "Add support for Behat tests (use AuthenticationManager)": "https://www.drupal.org/files/issues/2843505-8.patch"
            }
```
(and I have verified patches have been applied)

and in behat.yml default:extensions I have
```
 FriendsOfBehat\ServiceContainerExtension:
   imports:
     - "./web/modules/contrib/email_registration/behat.services.yml"
```
It looks to me like the 
```
    "autoload": {
        "psr-4": {
            "Drupal\\email_registration\\Component\\": "lib"
        }
    },
```
from the composer.json in email_registration is not working.  I have tried `composer dump-autoload` to rebuild the autoloads in case it was getting tangled in the patch application.

Any ideas?

**Comment by jonathanjfshaw** [comment]
Needs reroll after a small collision with #385 .

**Comment by jhedstrom** [comment]
I'd like to get this in soon so we can move forward with #62 and eventually #422. Is it possible to get those commits back from #339 or necessary? Either way, let's rebase/merge latest `master` and make sure tests are still passing here.

**Pull request closed without merging**
