### PR TITLE
Stop testing on PHP 5.3

### PR DESCRIPTION
**Pull request by pfrenssen**
PHP 5.3 has become unsupported years ago. Our test suite has been failing on the 5.3 tests for over a year now. This is slowing down the test runs.

Instead of spending time trying to fix it, let's just remove it from the matrix and move on.

### CODE REVIEW

**Comment by jhedstrom** [comment]
This looks good to me once the conflicts are resolved.

**Comment by haringsrob** [comment]
Resolved the conflict, this needs a merge before #324

**Comment by pfrenssen** [comment]
Thanks @haringsrob!

**Comment by pfrenssen** [comment]
Once this is in, let's also make a PR to drop PHP 5.4, that also needs to be done before we can merge #324.

**Pull request merged**
