### PR TITLE
Update ClassGenerator.php

### PR DESCRIPTION
**Pull request by aronbeal**
Resolution for https://www.drupal.org/node/2468659

### CODE REVIEW

**Comment by aronbeal** [comment]
I'm not sure why the above failed - this commit had nothing to do with Drush.

**Comment by jhedstrom** [comment]
I merged a fix for Drush (we had been tracking the master branch which just dropped support for 6). I'm re-running the tests now.

**Comment by jhedstrom** [comment]
@aronbeal could you rebase this off of the latest master? The tests are still running with the wrong version of drush.

**Comment by aronbeal** [comment]
No problem.  Replaced by https://github.com/jhedstrom/drupalextension/pull/278

**Pull request closed without merging**
