### PR TITLE
Configuration change step definitions for D8

### PR DESCRIPTION
**Pull request by acbramley**
Depends on https://github.com/jhedstrom/DrupalDriver/pull/76

Provides 2 step definitions, one to update basic config, one for more complex config (i.e arrays)

### CODE REVIEW

**Comment by jhedstrom** [comment]
It would be good to put this in a new context, say `ConfigContext`, and then also add a test or two in the `features/api.feature` (or add a new `config.feature` file).

**Comment by acbramley** [comment]
@jhedstrom sure, will add it to the todo list :)

**Comment by acbramley** [comment]
@jhedstrom ok, I've added config.feature and ConfigContext. For some reason I couldn't get the tests directly working in this project but I was able to test them in my main project and they passed.

**Comment by jhedstrom** [comment]
@acbramley I haven't had a chance to try and debug, but the error thrown is:

```
PHP Fatal error:  Call to undefined method Drupal\Driver\Cores\Drupal8::configGet() in /home/travis/build/jhedstrom/drupalextension/vendor/drupal/drupal-driver/src/Drupal/Driver/DrupalDriver.php on line 318
```
The build appears to be pulling in the correct version of the Drupal Drivers, so I'm not sure what is missing.

**Comment by acbramley** [comment]
@jhedstrom that is strange, looking into it now.

**Comment by acbramley** [comment]
I can't get the tests running locally, specifically for Drupal 8 installations. The default profile runs up until the point it needs zombie, so it's not to do with libraries or anything.

The error I get is:

````
vagrant@crimestatistics /var/www/site/vendor/drupal/drupal-extension $ ./vendor/bin/behat --profile=drupal8

PHP Fatal error:  Undefined class constant 'Symfony\Component\DependencyInjection\ContainerInterface::SCOPE_CONTAINER' in /var/www/site/web/core/lib/Drupal/Core/DependencyInjection/Container.php on line 21
````

**Comment by jhedstrom** [comment]
@acbramley you should be able to fix that error if you copy the `doc/_static/composer.json.d8` over the `composer.json` file, remove `composer.lock` and then re-run `composer install` (over in #253 I've added the symfony versions to the main `composer.json`, so this step won't be necessary in the future.

**Comment by acbramley** [comment]
@jhedstrom thanks a lot! I was able to confirm my tests pass with those changes.

Any ideas on how to get the travis build to pass?

**Comment by acbramley** [comment]
Woops.

**Comment by acbramley** [comment]
It doens't look like it's cloning the correct version of drupal driver, under the composer install task I see:

````
- Installing drupal/drupal-driver (dev-master db97680)
    Cloning db97680b6c1970a08ef38524139faba5aadee474
````

**Comment by jhedstrom** [comment]
These are running locally for me too. The only thing I can figure is that travis is running the wrong driver? I realize that the PR to the Drupal Drivers didn't add `configGet` to the `DriverInterface` itself. Can you open a new PR there that adds that, then once that's merged, this fail may provide further debugging info.

**Comment by acbramley** [comment]
No worries, here ya go https://github.com/jhedstrom/DrupalDriver/pull/78

**Comment by jhedstrom** [comment]
@acbramley sooo, it's the behat drush endpoint that is installing the old version of the drupal driver. I have no idea why this hasn't come up on previous tests. Checkout https://api.travis-ci.org/jobs/110841327/log.txt?deansi=true and search for `drupal-driver`. It later overwrites `dev-master` with version `1.1.5`.

**Comment by jhedstrom** [comment]
Can you try commenting out `  - test ${DRUPAL_VERSION} -ne 8 || composer require drush-ops/behat-drush-endpoint` in `.travis.yml` and see if things go green? That line shouldn't actually be needed afaik.

**Comment by acbramley** [comment]
Good catch, I guess it would only ever happen when adding new functions to the driver which may not have happened in a while? In any case, we'll see if this fixes it!

**Comment by acbramley** [comment]
Ah, now this is an error I saw locally, will try to fix soon.

**Comment by jhedstrom** [comment]
@acbramley I've traced the latest fail down to a Symfony 3 incompatibility. I opened https://github.com/drush-ops/behat-drush-endpoint/pull/2.

**Comment by acbramley** [comment]
@jhedstrom yak-shaving at its finest, nice work :)

**Comment by jhedstrom** [comment]
@acbramley the fix I just merged in #256 should get this passing if you want to rebase this.

**Comment by jhedstrom** [comment]
@acbramley actually I'm still perfecting the fix over in #257, so you may want to hold off.

**Comment by acbramley** [comment]
Nice work @jhedstrom

**Comment by jhedstrom** [comment]
Thanks for sticking with this @acbramley!

**Pull request merged**
