### PR TITLE
Move getContext() into RawDrupalContext from DrupalSubContextBase

### PR DESCRIPTION
**Pull request by jonathanjfshaw**
Split out of #392

### CODE REVIEW

**Comment by jonathanjfshaw** [comment]
```
// If this code is executed
// before a test scenario starts (e.g. in a `@BeforeScenario` hook) then the
// contexts cannot yet be retrieved.
```
I removed this comment as testing showed it to be untrue; `getContext()` works fine from a @BeforeScenario tagged function.

**Comment by jonathanjfshaw** [comment]
This method appears to be untested. My first commit omitted the use statement and so was actually broken, but passed on Travis.

**Comment by pfrenssen** [comment]
> I removed this comment as testing showed it to be untrue; getContext() works fine from a @beforescenario tagged function.

Can you check this with the latest version of Behat? This comment was added recently because it was discovered that this can no longer be used in `@BeforeScenario` in recent versions of Behat. It used to work in versions older than Behat 3.2.0.

See https://github.com/jhedstrom/drupalextension/issues/386

**Comment by jonathanjfshaw** [comment]
> Can you check this with the latest version of Behat?

I tried but ended up in dependency hell. I did discover though that my testing had been on Behat 3.1, so I think we should assume your previous results are right and I restored the comment.

**Comment by jhedstrom** [comment]
Merged latest master in #428.

**Pull request closed without merging**
