### PR TITLE
Register Drupal 6 core classes

### LINKED ISSUE #153: Add support for Drupal 6 for the drupalextension ~3.0
It would be great if the drupalextension would have support for Drupal 6,
given that using behat gives you a good foundation to update to 6.x to 8.x later this year.

Feel free to ping me on IRC to discuss stuff

Will open up the corresponding PRs in a minutre

### PR DESCRIPTION
**Pull request by dawehner**
Fixes #153

This just registers the classes provided by the other PR

### CODE REVIEW

**Comment by jhedstrom** [comment]
Thanks for this! I'm working to get the current test failures fixed before merging this in.

**Comment by jhedstrom** [comment]
Tests are now all green. As discussed on IRC though, can you add the feature file from https://github.com/jhedstrom/DrupalDriver/pull/26 as a test here? `behat.yml.dist` and `.travis.yml` will need to be updated accordingly.

**Comment by dawehner** [comment]
Sure, let's give it a try

**Comment by dawehner** [comment]
Expanded the support for taxonomy terms and tested it ... I guess in order to make the tests passing here, we need to commit the branch in drupal-driver itself?

On my local system they pass so far:
```
$ vendor/bin/behat -fprogress --profile=drupal6
...............
9 scenarios (9 passed)
15 steps (15 passed)
1m56.03s (8.57Mb)
```

**Comment by jhedstrom** [comment]
Can you temporarily update `composer.json` to point at your working branch in DrupalDriver? (See https://getcomposer.org/doc/05-repositories.md).

**Comment by dawehner** [comment]
Ah, clever idea

On Mon, Mar 23, 2015 at 7:52 PM, Jonathan Hedstrom <notifications@github.com

**Comment by jhedstrom** [comment]
Tests are green again if you want to rebase this.

**Comment by dawehner** [comment]
Maybe it would be a good idea now to squash the commits into one?

**Comment by jhedstrom** [comment]
I've merged the DrupalDriver PR, so you can now switch `composer.json` back. You can squish the commits if you like, but don't have to.

**Comment by dawehner** [comment]
Alright, let's "hop" its still green.

**Comment by jhedstrom** [comment]
Awesome! Thanks!

**Pull request merged**
