### PR TITLE
BeforeStep and AfterStep no longer support tags in Behat 3

### LINKED ISSUE #92: BeforeStep and AfterStep no longer support tags in Behat 3
Tags can no longer be used on BeforeStep and AfterStep hooks. This means that this code in MinkContext.php:

```
/**
   * For javascript enabled scenarios, always wait for AJAX after clicking.
   *
   * @AfterStep @javascript
   */
  public function afterJavascriptStep($event) {
    $text = $event->getStep()->getText();
    if (preg_match('/(follow|press|click|submit)/i', $text)) {
      $this->iWaitForAjaxToFinish();
    }
  }
```

is failing silently - the function is never called.

See https://github.com/Behat/Behat/issues/650 and https://github.com/Behat/Behat/issues/653.

### PR DESCRIPTION
**Pull request by pfrenssen**
Fixes #92.

### CODE REVIEW

**Comment by pfrenssen** [comment]
Also cherry-picked to the 3.2 branch: https://github.com/jhedstrom/drupalextension/commit/c174852531195711d367444c91e94029d23ca732

**Comment by jonathanjfshaw** [comment]
I'm not sure this is a good enough solution. The fix covers the case if a feature is tagged@javascript, but not if a scenario is tagged @javascript. And that difference is against usual Behat DX (in that we expect scenarios to inherit tag effects from their parent features) and is bound to catch people out.

[According to @everzet](https://github.com/Behat/Behat/issues/795) to get the expected result we have to "Use hooks and temporary state in your context (or trait). That's nasty, but will work.".

So how about:
```
  private $taggedJavascript;

    /**
    * @BeforeScenario @javascript
    */
   public function beforeScenario(BeforeScenarioScope $scope)
   {
      $this->taggedJavascript = true;
   }

   /**
    * @AfterScenario @javascript
    */
   public function afterScenario(AfterScenarioScope $scope)
   {
       $this->taggedJavascript = false;
   }

  /**
   * @BeforeStep
   */
  public function beforeJavascriptStep($event) {
    if ($this->taggedJavascript) {
      $text = $event->getStep()->getText();
      if (preg_match('/(follow|press|click|submit)/i', $text)) {
        $this->iWaitForAjaxToFinish();
      }
  }
```

**Comment by pfrenssen** [comment]
I didn't know this, sounds like a good suggestion. Unfortunately this PR is already merged, would it be possible to create a new one for this?

**Comment by jonathanjfshaw** [comment]
Sure. This gives us 4 javascript specific functions. Do you want to split these out into a javascript context for 4.x?

**Comment by pfrenssen** [comment]
Yes a separate context for this sounds like a really good idea.

**Comment by jonathanjfshaw** [comment]
We don't currently have a feature that tests this. Somewhere in the Drupal admin UI that uses AJAX could provide a test.

How about:
```
@javascript
Given I am logged in as an "administrator"
When I visit "/admin/structure/types/manage/page/form-display"
Then I should see not "Widget settings: Textfield"
When I press the "title_settings_edit" button
Then I should see "Widget settings: Textfield"
```

**Pull request merged**
