### PR TITLE
Provide an example that uses human readable field names

### PR DESCRIPTION
**Pull request by pfrenssen**
Recently support was added to Behat to do @transform on row-based tables: [PR #654: Add support for row table transformations](https://github.com/Behat/Behat/pull/654). This finally makes it possible to use human readable names for fields.

## Before

Up to now we were forced to use machine names which are not only ugly, but violate the BDD principle of using domain specific language:

```
When I am viewing a "post" content:
  | title                | Post title          |
  | body                 | Body text           |
  | field_post_reference | Page one, Page two  |
  | field_post_date      | 2015-02-08 17:45:00 |
```

## After

```
When I am viewing a "post" content:
  | title     | Post title          |
  | body      | Body text           |
  | reference | Page one, Page two  |
  | date      | 2015-02-08 17:45:00 |
```

Much better!

Note that this currently relies on code that has recently been committed to the master branch of Behat. We might want to wait on a new release of Behat before merging this in.

### CODE REVIEW

**Comment by pfrenssen** [comment]
Tests on PHP5.5+ are failing because of #225.

**Comment by pfrenssen** [comment]
Rebased on the latest master now that the fix for #225 is in.

**Comment by pfrenssen** [comment]
It's failing on Drupal 8.

**Comment by pfrenssen** [comment]
Going to work on this today.

**Comment by pfrenssen** [comment]
Forgot to update the separate `composer.json` file which is used for the D8 tests. This should be green now.

I personally think it is best to await a new release of Behat before merging this in, so that we do not depend on a development version. I will maintain this branch until Behat gets a new release.

**Comment by jhedstrom** [comment]
Thanks!

**Pull request merged**
