### PR TITLE
Add space arround the keywords to avoid wrongly matching.

### PR DESCRIPTION
**Pull request by weynhamz**
Trying to fix jhedstrom#560.

Maybe there is a better way.

### CODE REVIEW

**Comment by pfrenssen** [comment]
Thanks! Can you try with word boundaries?

```
'/\b(follow|press|click|submit)\b/i'
```

This is a more robust and "regexy" way to check for individual words in a string.

**Comment by weynhamz** [comment]
Thanks, @pfrenssen, just updated, the boundary check is better, I was just trying to have a quick fix.


Though I still do not think this is a good approach to trigger an AJAX wait, I am too familiar with Behat, is there a better way like using tags or listeners on click event/method to trigger it instead?

**Comment by pfrenssen** [comment]
Thanks!

I don't think it is possible to trigger methods asynchronously in a running PHP process from JS code due to the single threaded nature of PHP, and we are already limiting this on the `@javascript` tag. This is the best we can do that would work with all kinds of Drupal projects.

Of course in your own project you can extend `MinkExtension` and provide any logic that is specific to your project to narrow down the cases where this is triggered.

**Comment by jhedstrom** [comment]
Thanks!

**Pull request merged**
