### PR TITLE
Adding a drupal config that allows you to set a configuration parameter that keeps the content created during a test from being deleted.

### PR DESCRIPTION
**Pull request by scottalan**
This would allow you to use tests to create test content.

Reference Issue: https://github.com/jhedstrom/drupalextension/issues/135

### CODE REVIEW

**Comment by jhedstrom** [comment]
The build is failing claiming it can't find the config `keep_content`, which is odd, since I can see it declared in the diff.

**Comment by Trogie** [comment]
Very nice feature! Maybe add also an extra parameter so that content can also be deleted aftere the full feature, not after the scenario that created it?

**Comment by scottalan** [comment]
@jhedstrom I did see the build failed after I made a PR but didn't look at the build until just now. Hmmm, yeah. It's there.

**Comment by jhedstrom** [comment]
Closing this out as `1.x` is no longer supported, and due to inactivity.

**Pull request closed without merging**
