### PR TITLE
Use better technique to determine whether user is logged in - Backport

### PR DESCRIPTION
**Pull request by generalconsensus**
This P.R. is to backport the functionality that LionsAd did for the 1.0 release of Behat

### CODE REVIEW

**Comment by generalconsensus** [comment]
I see that I'm having guzzle errors, did I pick the wrong version of the source repo to merge against? @jhedstrom

**Comment by jhedstrom** [comment]
@generalconsensus no, that is the correct branch. I think perhaps the 1.x tests no longer pass (the blackbox tests are out of date, and I'm not exactly sure what the other failures indicate).

**Comment by generalconsensus** [comment]
@jhedstrom What should my next steps be, can I help?

**Comment by jhedstrom** [comment]
@generalconsensus I'll review the fails more closely, and merge this next week. I don't think any changes here have impacted the tests.

**Comment by generalconsensus** [comment]
@jhedstrom I know you are a busy man, not trying to bother much but my manual patching attempts (https://github.com/cweagans/composer-patches) don't work 100% of the time.

Just a friendly reminder that I appreciate the help :+1:

**Comment by jhedstrom** [comment]
Hmm, actually these errors in the tests `Unable to access the response content before visiting a page` look like a direct result of this updated logic. Something is trying to access a page before a page has been visited, and for some reason the catch bit in `loggedIn()` isn't properly handling that. If you can run the tests locally with `vendor/bin/behat --verbose` you may get some insight into what's happening.

**Comment by generalconsensus** [comment]
Closing as I don't have time to pursue patching older version

**Pull request closed without merging**
