### PR TITLE
Support for testing emails sent from Drupal

### PR DESCRIPTION
**Pull request by jonathanjfshaw**
Addresses #195.
Depends on parallel driver PR134: https://github.com/jhedstrom/DrupalDriver/pull/134.

A few architectural notes ...

## Service architecture

I had in mind the possibility that there could be fundamentally different mechanisms for handling test emails (e.g. Drupal core's test mail collector, contrib maillog, and IMAP) which could use the same context. Therefore I tried to put interacting with the mail store outside of the context as a service. The supplied implementation uses test mail collector.

However, I'm not clear yet on how do this in the Drupal extension and so it's not a real service for now, just a kind of service-like class. Hopefully though it will be relatively easy to upgrade to a real service in the future.

Abstracting in this way is responsible for a few minor complications that have no purpose in the default implementation such as 
*  the distinction between enabling/disabling email sending, and collecting/not-collecting emails. An IMAP service would want to send emails AND collect them, whereas for Drupal's test mail collector collecting always stops sending.
* the $store name passed when getting emails. Test mail collector is just one store, but different services, or combinations of services, could potentially be capturing emails into various different stores.

## Mink context
I needed to be able to visit pages in order to follow links from emails, but the context is extending RawDrupalContext not RawMinkContext. Therefore I moved getcontext() out of SubContextBase into it's parent RawDrupalContext and used this to help me load a minkContext and visit a page. Maybe there was an easier way of doing this.

### CODE REVIEW

**Comment by jonathanjfshaw** [comment]
There's a lot of helper functions in the MailContext. It's possible that these should be split out into a RawMailContext in order to make it easier for people to override the mail steps in their own projects.

**Comment by jhedstrom** [comment]
This is looking great! Thanks for working on this.

I agree that any non-step-definition code in `MailContext` should go into a `RawMailContext` to allow that to be re-used for folks that want to craft their own step-definitions.

**Comment by pfrenssen** [comment]
> I needed to be able to visit pages in order to follow links from emails, but the context is extending RawDrupalContext not RawMinkContext. Therefore I moved getcontext() out of SubContextBase into it's parent RawDrupalContext and used this to help me load a minkContext and visit a page. Maybe there was an easier way of doing this.

This is also a good idea! Can we maybe split this off to a separate PR?

**Comment by jonathanjfshaw** [comment]
Suggested changes by @jhestrom and @pfrenssen made. Tests are failing because this is blocked on the hunk split out into #396 and the supporting driver methods in jhedstrom/DrupalDriver#134.

**Comment by jhedstrom** [comment]
Thanks for this!

**Pull request merged**
