### PR TITLE
Field columns

### PR DESCRIPTION
**Pull request by pfrenssen**
Pull request for #182. This is 99% finished but I'm currently blocked by #193. Creating this pull request so that the work done so far is published. I might not have time to work on this in the next couple of weeks/months.

### CODE REVIEW

**Comment by jhedstrom** [comment]
This is looking great. Thanks for your continued work on this!

**Comment by pfrenssen** [comment]
I won't have time to work on this in the next weeks unfortunately :-/ I started on a new side project which will gobble up all my spare time.

**Comment by pfrenssen** [comment]
Starting on this again. Will first merge the upstream changes and run a test on Travis, then evaluate what still needs to be done.

**Comment by pfrenssen** [comment]
Great, this is now also working. I looked through the code and this seems to be complete and ready for review.

I will rebase the branch onto the latest upstream master and clean up the commits.

**Comment by burnsjeremy** [comment]
It must have been a one off error or something, when I ran composer update I was on v3.1.0 and v1.1.0 b/c I had checked that first. Anyway after swapping back my DrupalExtension from v3.0.12 to v3.1.0 it seems to have fixed itself (When I ran composer update it was the only package to update so DrupalDriver was on the correct version already). Sorry for the false alarm and thanks for the help.

**Pull request merged**
